//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2019-2022 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// LengthFieldPrependerTest+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LengthFieldPrependerTest {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (LengthFieldPrependerTest) -> () throws -> Void)] {
      return [
                ("testWrite3BytesOfUInt32Write", testWrite3BytesOfUInt32Write),
                ("testEncodeWithUInt8HeaderWithData", testEncodeWithUInt8HeaderWithData),
                ("testEncodeWithUInt16HeaderWithString", testEncodeWithUInt16HeaderWithString),
                ("testEncodeWithUInt24HeaderWithString", testEncodeWithUInt24HeaderWithString),
                ("testEncodeWithUInt32HeaderWithString", testEncodeWithUInt32HeaderWithString),
                ("testEncodeWithUInt64HeaderWithString", testEncodeWithUInt64HeaderWithString),
                ("testEncodeWithInt64HeaderWithString", testEncodeWithInt64HeaderWithString),
                ("testEncodeWithUInt64HeaderStringBigEndian", testEncodeWithUInt64HeaderStringBigEndian),
                ("testEncodeWithInt64HeaderStringDefaultingToBigEndian", testEncodeWithInt64HeaderStringDefaultingToBigEndian),
                ("testEmptyBuffer", testEmptyBuffer),
                ("testLargeBuffer", testLargeBuffer),
                ("testTooLargeForLengthField", testTooLargeForLengthField),
           ]
   }
}

