version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  test:
    image: swift-nio-extras:22.04-5.9
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  documentation-check:
    image: swift-nio-extras:22.04-5.9

  shell:
    image: swift-nio-extras:22.04-5.9
