version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"

  test:
    image: swift-nio-extras:20.04-5.5
    command: /bin/bash -xcl "cat /etc/lsb-release && swift -version && swift test -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  shell:
    image: swift-nio-extras:20.04-5.5
