version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"
        ubuntu_version: "focal"

  test:
    image: swift-nio-extras:20.04-main

  shell:
    image: swift-nio-extras:20.04-main
