version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:18.04-5.0
    build:
      args:
        ubuntu_version: "18.04"
        swift_version: "5.0"
        skip_ruby_from_ppa: "true"

  test:
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors"
    image: swift-nio-extras:18.04-5.0
