version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:18.04-5.4
    build:
      args:
        base_image: "swift:5.4-bionic"
        ubuntu_version: "bionic"
        swift_version: "5.4"

  test:
    image: swift-nio-extras:18.04-5.4
    command: /bin/bash -xcl "cat /etc/lsb-release && swift -version && swift test -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  shell:
    image: swift-nio-extras:18.04-5.4
