version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:20.04-5.5
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.5-focal"
        ubuntu_version: "focal"

  test:
    image: swift-nio-extras:20.04-5.5

  shell:
    image: swift-nio-extras:20.04-5.5
