version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-nio-extras:22.04-main
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  documentation-check:
    image: swift-nio-extras:22.04-main

  shell:
    image: swift-nio-extras:22.04-main
