version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:18.04-5.0
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.0"

  test:
    command: /bin/bash -xcl "swift test -Xswiftc -warnings-as-errors"
    image: swift-nio-extras:18.04-5.0
